steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['app', 'deploy']
timeout: '1600s'
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
serviceAccount: arboreal-path-434303-q1@appspot.gserviceaccount.com